# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRSm5ww5-81CSRSVNMTTjVpa62HmRcqf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random as rd

m_map={
    'Left':1,
    'Right':2
    
}
k_map={
    'Yes':1,
    'No':0
}

df=pd.read_csv('data.csv')
df=df.drop(columns=['ID','Photo','Name','Flag','Nationality','Club','Club Logo','Value','Wage','Special','Work Rate','Body Type','Jersey Number','Joined','Loaned From','Contract Valid Until','Height','Weight','LS','ST','RS','LW','LF','CF','RF','RW','LAM','CAM','RAM','LM','LCM','CM','RM','LWB','LDM','CDM','RDM','RWB','LB','LCB','CB','RCB','RB','Release Clause','RCM'])
df=df.dropna(how='any')
df['Preferred Foot']=df['Preferred Foot'].map(m_map)
df['Real Face']=df['Real Face'].map(k_map)
df['POS']=df['Position']
df=df.drop(columns=['Position','Unnamed: 0'])
display(df)

X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)
Y

import scipy.cluster.hierarchy as sch
dendrogram = sch.dendrogram(sch.linkage(X, method = 'ward'))
plt.title('Dendrogram')
plt.xlabel('Players')
plt.ylabel('Euclidean distances')
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters = 26, affinity = 'euclidean', linkage = 'ward')
y_pred= hc.fit_predict(X)

from sklearn import metrics
metrics.adjusted_rand_score(Y,y_pred)

metrics.adjusted_mutual_info_score(Y,y_pred)